### 创建用户
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "wangwu",
  "email": "hugh@qq.com",
  "password": "123456"
}

### 删除用户
DELETE http://localhost:3000/users/7
Authorization: ""

### 更新用户
Put http://localhost:3000/users/8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxpc2kiLCJzdWIiOjgsImlhdCI6MTc0Mzk5MTQ4MiwiZXhwIjoxNzQzOTk1MDgyfQ.apI1WSqB4RWsDtRJqIaYjU9ZWRR70foEmShzSG09O-I

{
  "username": "lisi",
  "email": "lisi@lookout.com"
}

### 获取所有用户
GET http://localhost:3000/users

### 获取单个用户
GET http://localhost:3000/users/1