### 创建用户
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "张三",
  "email": "hugh@qq.com",
  "password": "123456"
}

### 删除用户
DELETE http://localhost:3000/users/1

### 更新用户
Put http://localhost:3000/users/2
Content-Type: application/json

{
  "username": "李四",
  "email": "lisi@example.com"
}

### 获取所有用户
GET http://localhost:3000/users

### 获取单个用户
GET http://localhost:3000/users/1